export const INIT_BUBBLES_SCORES = 'INIT_BUBBLES_SCORES';
export const INIT_BUBBLES = 'INIT_BUBBLES';
export const ADD_BUBBLE = 'ADD_BUBBLE';
export const DELETE_BUBBLE = 'DELETE_BUBBLE';
export const UPDATE_BUBBLE = 'UPDATE_BUBBLE';

export const SAGA_INIT_BUBBLES = 'SAGA_INIT_BUBBLES';
export const SAGA_ADD_BUBBLE = 'SAGA_ADD_BUBBLE';
export const SAGA_DELETE_BUBBLE = 'SAGA_DELETE_BUBBLE'; 
export const SAGA_UPDATE_BUBBLE = 'SAGA_UPDATE_BUBBLE';